apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paybills-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paybills.ng
        - api.paybills.ng
      secretName: paybills-tls
  rules:
    - host: paybills.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paybills-frontend
                port:
                  number: 80
    - host: api.paybills.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paybills-backend
                port:
                  number: 80
